### ISSUE TITLE
Fail with move function

### ISSUE THREAD

**Issue by AaronIngRother** [coppolaemilio/godot-nightly#5]
Hi, 

I have used this Godot project but it do not work fine for me. When I move the window, this is moved with move shaking and not with uniform move.

Why did this happen?

My version of Godot is 3.5.3

**Comment by coppolaemilio** [comment]
The project was pulling the builds from a server that no longer exists, I will archive it since it is abandoned. It wasn't too hard to make, so you can probably try to port it to Godot 4 and make it pull the builds from somewhere else, but at this point I don't have the bandwidth to work on it. Thanks for the interest though 😅
